#pragma config(Sensor, dgtl1,  e_stop_touch,   sensorTouch)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           frontLeft,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task e_stop() {
	untilTouch(e_stop_touch);
	stopAllTasks();
}
float frontRightMult = 1;
float frontLeftMult = 1;
int speed = 100;

void driveForward(float time) {
	startMotor(frontLeft,speed*frontLeftMult);
	startMotor(frontRight,speed*frontRightMult);
	// move forward time
	wait(time);

	stopMotor(frontLeft);
	stopMotor(frontRight);
}
void rotate(short m, short m2, float time) {
	startMotor(m,speed);
	startMotor(m2, -1*speed);
	wait(time);
	stopMotor(m);
	stopMotor(m2);
}
task main()
{
	startTask(e_stop);
	// Config
	bool isRight = true;
	float forwardTime = 1.5;
	float rotateTime = 0.5;


	while (true) {

		// drive forward
		// turn 90 degrees
		driveForward(forwardTime);
		if (isRight) {
			rotate(frontLeft,frontRight,rotateTime);
			}else {
			rotate(frontRight,frontLeft,rotateTime);
		}

	}

}
