#pragma config(Motor,  port1,           fr,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           fl,            tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	float waitTime = 2;
	while (true) {
		startMotor(fr);
		wait(waitTime);
		stopMotor(fr);
		startMotor(fl);
		wait(waitTime);
		stopMotor(fl);
	}


}
