#pragma config(Sensor, dgtl1,  e_stop_touch,   sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task e_stop() {
	untilTouch(e_stop_touch);
	stopAllTasks();
}

task main() {
	startTask(e_stop);


}
