#pragma config(Sensor, dgtl1,  e_stop_touch,   sensorTouch)
#pragma config(Motor,  port2,           fr,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           fl,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           br,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           bl,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task e_stop() {
	untilTouch(e_stop_touch);
	stopAllTasks();
}
void go(int speed) {
	startMotor(fr,speed);
	startMotor(fl,speed);
	startMotor(br,speed);
	startMotor(bl,speed);
}
task main() {
	startTask(e_stop);
	while (true){
		go(127);
	}
}
