#pragma config(Sensor, dgtl1,  greenLight,     sensorDigitalOut)
#pragma config(Sensor, dgtl2,  redLight,       sensorDigitalOut)
#pragma config(Sensor, dgtl3,  sonarl,         sensorSONAR_cm)
#pragma config(Sensor, dgtl5,  sonarr,         sensorSONAR_cm)
#pragma config(Motor,  port2,           r,             tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           l,             tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int threshold = 20;
int minSpeed = 0;
int maxSpeed = 127;



task main()
{
	while (true){
		int a = SensorValue[sonarl];
	//startMotor(r);
		//startMotor(l);
	}
}
